language: c
before_script:
  - sudo apt-get update
  - sudo apt-get install libibverbs-dev libnl-dev
  # the system provided rdmacm is too old
  - pushd /tmp && wget https://www.openfabrics.org/downloads/rdmacm/librdmacm-1.0.16.tar.gz && tar xvfz librdmacm-1.0.16.tar.gz && cd librdmacm-1.0.16 && ./configure CC=gcc && make -j && sudo make install && popd
script: ./autogen.sh && ./configure && make -j && make check
compiler:
  - gcc
  - clang

notifications:
  email: false
